name = "Dartis-Craft - Testing 1 - Vanilla Plus"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9315b56f1a75fe403cb6d48faec0fbd8a7634e2562a3c579a85713ab9612ab7c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
